version = 1

test_patterns = [
  "tests/**",
  "test_*.py"
]

exclude_patterns = [
  "bin/**",
  "**/node_modules/"
]

# Python analyzer
[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

# Docker analyzer
[[analyzers]]
name = "docker"
enabled = true