dist: bionic

language: python

os:
  - linux

services:
  - docker

cache:
  pip: true
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
    - python3-pip
    - python3-setuptools

before_script:
  # build docker images development
  - sudo docker-compose -f local.yml build
  # build docker images production
  - cp -r .envs/.local/ .envs/.production/
  # - sudo docker-compose -f production.yml build
  # add test groups for group import command
  - cp compose/local/flask/meetup_groups/test-groups.json meetup_groups/test-groups.json

install:
  # install docker-compose
  - pip3 install docker-compose wheel

script:
  # run tests
  - sudo docker-compose -f local.yml run flask coverage run -m pytest
  # run typing check with mypy
  - sudo docker-compose -f local.yml run flask coverage run -m mypy /app

# code coverage
after_success:
  - echo TRAVIS_JOB_ID=$TRAVIS_JOB_ID >> .envs/.local/.flask
  - echo TRAVIS_BRANCH=$TRAVIS_BRANCH >> .envs/.local/.flask
  - echo COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN >> .envs/.local/.flask
  - sudo docker-compose -f local.yml run flask coverage report -m
  - sudo docker-compose -f local.yml run flask coveralls